# device resolution
#OF_SCREEN_H=2400
OF_STATUS_H=70
OF_STATUS_INDENT_LEFT=80                                                                                     
OF_STATUS_INDENT_RIGHT=80
OF_HIDE_NOTCH=1
OF_CLOCK_POS=1

#specific instructions
OF_USE_GREEN_LED=0
OF_ENABLE_FRP_ADDON=1
OF_DEVICE_WITHOUT_PERSIST=1
OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
OF_DONT_PATCH_ON_FRESH_INSTALLATION=1
OF_NO_TREBLE_COMPATIBILITY_CHECK=1
OF_DONT_PATCH_ENCRYPTED_DEVICE=0
OF_USE_LEGACY_BATTERY_SERVICES=1
OF_FLASHLIGHT_ENABLE=0

# Decrypt/Encrypt
OF_SKIP_FBE_DECRYPTION=1
OF_DONT_PATCH_ENCRYPTED_DEVICE=0
